FROM node:14.21.3

# Define de the working directory
WORKDIR /usr/src/gestion_backend

# Install app dependencies
COPY package.json ./

RUN npm install --force

# Set deploy enviroment

#ENV NODE_ENV production
ENV NODE_ENV dev

# Bundle app source
COPY . .

EXPOSE 4001
#EXPOSE 80

ENTRYPOINT [ "node" ]

CMD [ "./server.js" ]